### ISSUE TITLE
no matches for kind "Deployment" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by kholisrag** [jfelten/gitea-helm-chart#45]
@jfelten 
hello
I have values.yaml
```
ingress:
  enabled: true
service:
  http:
    externalHost: gitea.example.com
persistence:
  enabled: true
  giteaSize: 10Gi
  accessMode: ReadWriteOnce
  storageClass: standard
  annotations:
    "helm.sh/resource-policy": keep
dbType: "postgres"
useInPodPostgres: true
externalDB:
  dbUser: xxx
  dbPassword: xxx
  dbHost: postgresql.database.svc.cluster.local
  dbPort: 5432
  dbDatabase: personal_gitea
```

but when I install :
```
helm repo add jfelten https://jfelten.github.io/helm-charts/charts
helm upgrade -i --atomic --wait --timeout 10m0s -n git -f values.yaml gitea jfelten/gitea

```
have the following stderr:
```
Release "gitea" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1"
```

is your github.io page not updated yet? or something else?
as I notice that deployment.yaml template already have have version deployment v1

CMIIW, and please help
